/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MvcClientesIV.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    split: false,
                    height: 29,
                    html: [
                        '<div class="textHeader">MvcClientesIV Aplicaciòn para Facturación de Clientes</div>'
                    ],
                    itemId: 'headerPanel',
                    style: 'background:#15428B;font-size: 25px; text-align: left',
                    layout: 'fit'
                },
                {
                    xtype: 'panel',
                    flex: 0,
                    region: 'west',
                    split: true,
                    border: '0 2 0 0',
                    itemId: 'menuPanel',
                    width: 192,
                    bodyBorder: false,
                    collapsed: false,
                    collapsible: true,
                    iconCls: 'sitemap',
                    title: 'Menu Principal',
                    titleAlign: 'center',
                    layout: {
                        type: 'accordion',
                        titleCollapse: false,
                        sequence: true,
                        multi: true
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            itemId: 'tlBarMenuPanel',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnSalirSistema',
                                    iconCls: 'salir',
                                    text: 'Salir del Sistema'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    split: true,
                    itemId: 'contentPanel',
                    layout: 'fit',
                    collapsed: false,
                    items: [
                        {
                            xtype: 'tabpanel',
                            itemId: 'tabPanelMain',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    html: '<body scroll="no"> <!-- Start page content --> <div id="start-div"> 	<div style="float:left;" ><img src="resources/imagenes/Welcome.png" /></div> 	<div style="margin-left:100px;"> 	    <h2 style="display: block; border-bottom: 1px solid teal;padding-bottom: 4px;">Bienvenidos</h2> 	    <p>Creado y Desarrollado por INITEC Software, Para los Amigos de  la comunidad ExtJs</p> 	    <h2 style="display: block; border-bottom: 1px solid teal;padding-bottom: 4px;">Si te gusto el proyecto puedes hacer una donacion,escribiendome a: delphiiceberg@gmail.com</h2>    </div>   	 </body>',
                                    layout: 'fit',
                                    iconCls: 'tabs',
                                    title: 'Pagina principal'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 25,
                    html: [
                        'IcebergDelphi.-2013.- Extjs ver. 4.2.1'
                    ],
                    itemId: 'southPanel'
                }
            ]
        });

        me.callParent(arguments);
    }

});