/*
 * File: app/controller/menu/Menu.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MvcClientesIV.controller.menu.Menu', {
    extend: 'Ext.app.Controller',

    models: [
        'menu.Item',
        'menu.Root'
    ],
    stores: [
        'menu.Menu'
    ],

    refs: [
        {
            ref: 'tabPanelMain',
            selector: '#tabPanelMain'
        }
    ],

    onPanelRender: function(component, eOpts) {
        var menuPanel =Ext.ComponentQuery.query('panel#menuPanel')[0];
        this.getMenuMenuStore().load(function(records, op, success){
            Ext.each(records, function(root){
                    var menu = Ext.create('MvcClientesIV.view.menu.Item',{
                    title: root.get('text'),
                    iconCls: root.get('iconCls')
                });

                Ext.each(root.raw.items, function(itens){
                    Ext.each(itens, function(item){
                            menu.getRootNode().appendChild({
                            text: item.text,
                            leaf: true,
                            iconCls: item.iconCls,
                            id: item.id,
                            className: item.className
                        });
                    });
                });

                menuPanel.add(menu);


            });

        });
    },

    onTreePanelItemSelect: function(dataview, record, item, index, e, eOpts) {
        var mainPanel = this.getTabPanelMain();
        var newTab = mainPanel.items.findBy(
            function (tab){
                return tab.title === record.get('text');
            });

        if (!newTab){
            newTab = mainPanel.add({
                xtype: record.raw.className,
                closable: true,
                iconCls: record.get('iconCls'),
                title: record.get('text')
            });
        }

        mainPanel.setActiveTab(newTab);

    },

    init: function(application) {
        this.control({
            "#menuPanel": {
                render: this.onPanelRender
            },
            "mainmenuitem": {
                itemclick: this.onTreePanelItemSelect
            }
        });
    }

});
