/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true,
    paths: {
        Ext: 'ext/src'
    }
});


Ext.application({

    requires: [
        'Ext.Loader',
        'Ext.ux.grid.SelectSearch',
        'MvcClientesIV.util.SessionMonitor'
    ],
    views: [
        'MainView',
        'menu.Item'
    ],
    controllers: [
        'menu.Menu',
        'clientes.Clientes'
    ],
    name: 'MvcClientesIV',

    launch: function() {
        Ext.create('MvcClientesIV.view.MainView');
        /*Si descomentas esta lina, comenzara el monitoreo de seseion*/
        //MvcClientesIV.util.SessionMonitor.start();
    }

});
