/*
 * File: app/view/clientes/Captura.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MvcClientesIV.view.clientes.Captura', {
    extend: 'Ext.window.Window',
    alias: 'widget.clientesCaptura',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    autoShow: true,
    height: 194,
    itemId: 'winCapturaClientes',
    width: 411,
    layout: 'fit',
    title: 'Captura/Ediación',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'frmCapturaClientes',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'edtCliente',
                            width: 525,
                            fieldLabel: 'Cliente',
                            name: 'Cliente',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'cboSexo',
                            fieldLabel: 'Sexo',
                            name: 'Sexo',
                            store: [
                                'M',
                                'F'
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            width: 400,
                            fieldLabel: 'Edad',
                            name: 'Edad',
                            hideTrigger: true
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'edtId',
                            fieldLabel: 'Label',
                            name: 'idcliente'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Limite de Credito',
                            name: 'id_limitecredito',
                            editable: false,
                            displayField: 'descripcion',
                            store: 'catalogos.LimiteCredito',
                            valueField: 'idlimite'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            iconCls: 'guardar',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCancelar',
                            iconCls: 'cancelar',
                            text: 'Cancelar'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});