/*
 * File: app/store/catalogos/LimiteCredito.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MvcClientesIV.store.catalogos.LimiteCredito', {
    extend: 'Ext.data.Store',

    requires: [
        'MvcClientesIV.model.catalogos.Limitecredito',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            autoSync: true,
            model: 'MvcClientesIV.model.catalogos.Limitecredito',
            storeId: 'catalogos.LimiteCredito',
            proxy: {
                type: 'ajax',
                actionMethods: {
                    read: 'POST'
                },
                api: {
                    read: 'controller_catalogos/readLimiteCredito'
                },
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});